version: '3.7'
services:
        mysql-standalone:
                image: 'mysql:5.6'
                environment:
                        - MYSQL_ROOT_PASSWORD=password
                        - MYSQL_PASSWORD=password
                        - MYSQL_DATABASE=achatdb
                        - MYSQL_USER=dorsaf
                ports:
                        - "3306:3306"
        springboot-docker-container:
                build:
                        context: .
                container_name: spring-boot-docker-container
                image: dora12334/bdrepo
                ports:
                        - '8082:8082'
                depends_on:
                        - mysql-standalone
                environment:
                        SPRING_DATASOURCE_URL: jdbc:mysql://172.10.0.140:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
                        SPRING_DATASOURCE_USERNAME: "dorsaf"
                        SPRING_DATASOURCE_PASSWORD: "password"
volumes:
        dbvol:
